// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgM9dr_1oWdalGgLsnvuxisI7DzsRb0XQ',
    appId: '1:272472365314:android:ea8517a7164936a19f0a1b',
    messagingSenderId: '272472365314',
    projectId: 'esperflow-1b828',
    storageBucket: 'esperflow-1b828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjraLaqeWgoDN9_gxbf5Zu8De6eyTGIAU',
    appId: '1:272472365314:ios:147f9b659ea35d299f0a1b',
    messagingSenderId: '272472365314',
    projectId: 'esperflow-1b828',
    storageBucket: 'esperflow-1b828.firebasestorage.app',
    iosBundleId: 'com.example.esperflow',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgYb8tE8QMD5dJ_j0wOXYW3uH7g3NCBkc',
    appId: '1:272472365314:web:b60a8aef9679ee419f0a1b',
    messagingSenderId: '272472365314',
    projectId: 'esperflow-1b828',
    authDomain: 'esperflow-1b828.firebaseapp.com',
    storageBucket: 'esperflow-1b828.firebasestorage.app',
    measurementId: 'G-WLVW8B6FNJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjraLaqeWgoDN9_gxbf5Zu8De6eyTGIAU',
    appId: '1:272472365314:ios:147f9b659ea35d299f0a1b',
    messagingSenderId: '272472365314',
    projectId: 'esperflow-1b828',
    storageBucket: 'esperflow-1b828.firebasestorage.app',
    iosBundleId: 'com.example.esperflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgYb8tE8QMD5dJ_j0wOXYW3uH7g3NCBkc',
    appId: '1:272472365314:web:23bfdebe1a0023b69f0a1b',
    messagingSenderId: '272472365314',
    projectId: 'esperflow-1b828',
    authDomain: 'esperflow-1b828.firebaseapp.com',
    storageBucket: 'esperflow-1b828.firebasestorage.app',
    measurementId: 'G-Z41JBYY8J3',
  );

}