// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQV2HHYdBnzyMLWzOHbhTe10YHJs4CBcw',
    appId: '1:419345748826:web:24a74b65933a2eec9fd963',
    messagingSenderId: '419345748826',
    projectId: 'esperflow-638ad',
    authDomain: 'esperflow-638ad.firebaseapp.com',
    storageBucket: 'esperflow-638ad.firebasestorage.app',
    measurementId: 'G-SZZZ8JSB12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARZ7SJF7wKg5DsWGUnrNbESc4v4NWv1m8',
    appId: '1:419345748826:android:850709a45a43e8969fd963',
    messagingSenderId: '419345748826',
    projectId: 'esperflow-638ad',
    storageBucket: 'esperflow-638ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgK-E6AVnG4wsya5IR2uRtHmjwpKsrSkY',
    appId: '1:419345748826:ios:befe18e3114a9e429fd963',
    messagingSenderId: '419345748826',
    projectId: 'esperflow-638ad',
    storageBucket: 'esperflow-638ad.firebasestorage.app',
    iosBundleId: 'com.example.esperflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgK-E6AVnG4wsya5IR2uRtHmjwpKsrSkY',
    appId: '1:419345748826:ios:befe18e3114a9e429fd963',
    messagingSenderId: '419345748826',
    projectId: 'esperflow-638ad',
    storageBucket: 'esperflow-638ad.firebasestorage.app',
    iosBundleId: 'com.example.esperflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQV2HHYdBnzyMLWzOHbhTe10YHJs4CBcw',
    appId: '1:419345748826:web:6f25c299f51c90839fd963',
    messagingSenderId: '419345748826',
    projectId: 'esperflow-638ad',
    authDomain: 'esperflow-638ad.firebaseapp.com',
    storageBucket: 'esperflow-638ad.firebasestorage.app',
    measurementId: 'G-EWRMKG20YY',
  );
}
